### ISSUE TITLE
Error when play media attempted

### ISSUE THREAD

**Issue by jazzcpuguy** [onlyoneme/home-assistant-custom-components-wiim#3]
Here is the error returned by Home Assistant: This error originated from a custom integration.

Logger: custom_components.wiim_custom.media_player
Source: custom_components/wiim_custom/media_player.py:834
Integration: WiiM (documentation, issues)
First occurred: 12:56:17 PM (1 occurrences)
Last logged: 12:56:17 PM

For: Klipsch Invalid media type music. Only url is supported

I installed the custom component v0.2.2 today using HACS custom integration.  No errors when starting up and the entity is reflected as using the Wiim integration.  Specifying a content type is required when using the media_player.play_media command.  Would appreciate any insight as to how to fix or workaround this and I look forward to getting my Wiim Mini working at some point!

**Comment by onlyoneme** [comment]
What exactly did you try to do?

**Comment by jazzcpuguy** [comment]
Since this was all new and I wanted to see if it would work, I went into Developer Tools and tried to use a manual play media call from the services tab.  This is where the error occurred.  I did just attempt to access the media player and the browsed to a radio station from within HA and that WORKED!  Not sure where my problems lie but knowing that it does work, I will experiment further.  Again, if you have additional insights as to proper use, it would be appreciated.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by onlyoneme** [comment]
There is a dedicated service method to play an url - wiim_custom.play_url
Can you please try this one?

**Comment by jazzcpuguy** [comment]
Very good!  Used it and it worked great!  There is about a 2-3 second lag between issuing command and sound being heard but works!

So now that that basic question is answered, are there other commands that can be used such as setting volume on the device, issuing a media stop command to it which would it stop a stream that is in progress?  I am hoping to use my Wiim mini to generate a loud siren sound in conjunction with the HA Alarm I have configured.  I want it to increase the sound volume during an event, then lowerit to back to a ‘normal’ level when done.  All of this is through automations.

Truly appreciate you creating this and making my Wiim much more usable now.  By default, HA wanted it to be defined as a DLNA Device but that did not work well.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by onlyoneme** [comment]
Regarding other service commands, you can use most of those available for media_player. To call a preset playlist you can use wiim_custom.preset.

Unfortunately you cannot control the volume as I didn't implement it because I use only fixed volume...

**Comment by jazzcpuguy** [comment]
Very good.  Thanks for the feedback!  Volume control could perhaps be a future enhancement?  Now that I understand more, will continue to experiment.  Thank you for the prompt responses.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by onlyoneme** [comment]
I've just added volume control.
Fixed volume must be disabled in the WiiM app to get it working for the selected device.
