### ISSUE TITLE
Sync not with Tidal

### ISSUE THREAD

**Issue by Github-Axel** [onlyoneme/home-assistant-custom-components-wiim#8]
Hi,

Thank you for your works.
Happy to find an integration for Wiim product for HA.

- I use a Wiim pro (I will try a mini in a week)
- Home Assistant 2023.5.2
  Supervisor 2023.04.1
  Operating System 10.1
  Interface utilisateur : 20230411.1 - latest
- home-assistant-custom-components-wiim v0.2.3 or v0.3.4-beta

If I use Spotify, It"s works perfectly, but with tidal, it's sync not.
With Spotify
![image](https://user-images.githubusercontent.com/112357865/236629228-33a9ab82-7b32-4b0c-a2b5-e99935ea2596.png)
With Tidal
![image](https://user-images.githubusercontent.com/112357865/236629312-d35ea776-6495-41d1-9127-21cc64a538f1.png)

With WIIM app or 4STREAM all sync perfectly.
I also try Linkplay component but unsupport the Wiim product, a had a error in the log.

Any ideas ?

Thank you for your help and work !

**Comment by onlyoneme** [comment]
How do you use Tidal service? Is it from the WiiM Home app?

**Comment by Github-Axel** [comment]
Hi, 

I use the tidal app to play my music (version 2.81.0 on Android) than use tidal connect in the app and select the wiin (Living room)
![image](https://user-images.githubusercontent.com/112357865/236647120-ddbba0f2-2dec-4226-9ebb-1cbd1120643c.png)

When I open the wiim app, I can see the song currently playing.

**Comment by onlyoneme** [comment]
Can you show me what WiiM attributes are visible when you play any Tidal content? I mean Developer Tools / States in HA for your WiiM device.

**Comment by Github-Axel** [comment]
Hi,
Sorry for my late response, I was not at home this wkd.
With Tidal
![image](https://user-images.githubusercontent.com/112357865/236850357-580856f7-fa46-406f-848b-4c39ea466886.png)

With Spotify
![image](https://user-images.githubusercontent.com/112357865/236851002-dffae043-1eef-4197-b3e1-30b302dff91c.png)

**Comment by onlyoneme** [comment]
I think it's a parse issue for song metadata over UPnP. I'll send you my work-in-progress build to let you verify if it helps.

**Comment by onlyoneme** [comment]
Please try this one:
https://drive.google.com/file/d/1Vr-_EXPQTsN_GjXFuPhyqIJSmxUt9JHz/view

**Comment by Github-Axel** [comment]
Yeahhh !!! It works !!! 
![image](https://user-images.githubusercontent.com/112357865/236872231-4a9fda4f-614b-417c-b813-37c497dba1ae.png)

![image](https://user-images.githubusercontent.com/112357865/236871193-6ceca0d4-a5de-46c7-b4b1-8ff5ada29dbf.png)
A big thank you ! 
Great job 
![image](https://user-images.githubusercontent.com/112357865/236871958-eaa13905-8851-45c7-ba21-55c84cbf7043.png)

**Comment by onlyoneme** [comment]
I'm glad it helped, but it's a preliminary build so other issues are possible here.

**Comment by Github-Axel** [comment]
No problem at all, I will give you my feedback.

Any ideas why the bit rate stay at 96kbps ? I don't know if there any impact. If think not.

I found the log of the Wiim app (Windows)

`2023-05-08 19:06:57,968 [Thread-30   ] [DEBUG]  parse <class 'LPUPnPObserverManager.LPRenderTransportParser'>, <Event xmlns="urn:schemas-upnp-org:metadata-1-0/AVT/">
<InstanceID val="0">
<CurrentTrack val="0"/>
<NumberOfTracks val="0"/>
<CurrentTrackMetaData val="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:song=&quot;www.wiimu.com/song/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;
&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;
&lt;item id=&quot;0&quot;&gt;
&lt;song:subid&gt;&lt;/song:subid&gt;
&lt;song:description&gt;&lt;/song:description&gt;
&lt;song:skiplimit&gt;0&lt;/song:skiplimit&gt;
&lt;song:id&gt;&lt;/song:id&gt;
&lt;song:like&gt;0&lt;/song:like&gt;
&lt;song:singerid&gt;0&lt;/song:singerid&gt;
&lt;song:albumid&gt;0&lt;/song:albumid&gt;

&lt;song:actualQuality&gt;LOSSLESS&lt;/song:actualQuality&gt;

&lt;song:mqa&gt;0&lt;/song:mqa&gt;
&lt;song:atmos&gt;0&lt;/song:atmos&gt;
&lt;song:rate_hz&gt;44100&lt;/song:rate_hz&gt;
&lt;song:format_s&gt;16&lt;/song:format_s&gt;

&lt;song:bitrate&gt;737&lt;/song:bitrate&gt;

&lt;res protocolInfo=&quot;http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;&quot; duration=&quot;00:04:29.000&quot;&gt;&lt;/res&gt;
&lt;dc:title&gt;No Walls In The West&lt;/dc:title&gt;
&lt;dc:creator&gt;City of the Sun&lt;/dc:creator&gt;
&lt;upnp:artist&gt;City of the Sun&lt;/upnp:artist&gt;
&lt;upnp:album&gt;City of the Sun&lt;/upnp:album&gt;
&lt;upnp:albumArtURI&gt;https://resources.tidal.com/images/d48301c6/ecaf/4aa9/8dfb/1fdd1643eaba/640x640.jpg&lt;/upnp:albumArtURI&gt;
&lt;/item&gt;
&lt;/DIDL-Lite&gt;
"/>

**Comment by onlyoneme** [comment]
No impact, it's only informative. I do not face your issue, a bitrate I can see is the same as shown in the WiiM app.

**Comment by Github-Axel** [comment]
Okay.
Have a good day or night ^^
